// next modules
import Head from 'next/head';
// components
import Header from '../src/components/Header';
import SubHeader from "../src/components/SubHeader";
import TodoList from '../src/components/TodoList';

// styles
import cls from '../src/styles/TodoList.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg " />
      </Head>
      <main className={cls.main}>
        <header>
          <div className="container">
            <div className="row">
              <Header />
            </div>
          </div>
        </header>
        <section className={cls.subHeader}>
          <div className="container">
            <div className="row">
              <SubHeader title="You’ve got 7 task today " />
            </div>
          </div>
        </section>
        <section className={cls.TodoList}>
          <div className="container">
            <div className="row">
              <TodoList />
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
